### ISSUE TITLE
Activity type is not transfered from watch to tcx

### ISSUE THREAD

**Issue by knedlyk** [mru00/crane_gps_watch#12] opened 2015-03-04 12:53 UTC
It doesn't matter which activity I set in the watch settings, Cycling or else, the resulting tcx file has the only one Running activity. It gets a little bit annoying when I have to change the activity type all the time after uploading my tcx file to strava.com.

**Comment by mru00** [comment] 2015-03-13 18:28
That is strange. It should. Can't test it right now, but I remember that I have implemented and tested that feature (https://github.com/mru00/crane_gps_watch/blob/master/src/TcxWriter.cpp#L78)

Does the console output the correct activity (using the "--verbose" option)?
The same information is used in the console output (https://github.com/mru00/crane_gps_watch/blob/master/src/DataTypes.cpp#L105).

If the console output is also wrong, the error is in the parser. Then please post your firmware version and send me two images, one running, one cycling. It might be depended on the fw version.

If the console output is correct, I will need to dig further to find the error.

**Comment by knedlyk** [comment] 2015-05-09 17:20
Ok, I have the following settings: 
Workout->Profiles->Select = Cycling 
Workout->SportMod = Cycling 
Console output gave me the incorrect activity type, the output is Running, but must be Cycling:
$ crane_gps_watch_client --verbose
Autodetecting serial ports
Opening serial port '/dev/ttyUSB0'
Connected to watch on '/dev/ttyUSB0'
memory block #0 + 0
watch begin p=Running l=English version='Ver1.20' version2='.00.00.00.01.00.08.07.00.20' firmware='1.20.21_DLES0_00' timezone=26=0x1a
memory block #1 + 8
XmlFileWriter: writing to 2015-05-09_19-06-04.tcx

 workout info p=Running t=2015-05-09T18:08:17+02:00 d=01:26:31=5191 nsamples=1589=0x635
  track begin
  track end
 workout end samples with gps=1537 samples=1593 avg_time_diff=1.99812 d=3175.01

watch end
1 workouts read from watch

Here you can find "cycling" image file with those settings: https://www.dropbox.com/s/bc8qly7udg11d2f/image_must_be_cycling_but_not?dl=0
The running image I'll add later.
Best,
Yarema

**Comment by knedlyk** [comment] 2015-06-30 21:17
"Running image": https://www.dropbox.com/s/8sm60trna1zb0if/running?dl=0 .
Sorry for the delay.

**Comment by mru00** [comment] 2015-07-18 15:36
This must be caused by your firmware version;
Strange: your .bin files show another sorting in the list of profiles.

Mine: Running; cycling; hiking; sailing; other
yours: cycling; running; hiking; sailing; other

I can't find any clue to where the profile is stored in your bin files. Well, there is one byte, once "1" and once "0" in your bin files; i would need more samples to confirm that.

**Comment by knedlyk** [comment] 2015-07-18 19:22
Well, maybe it's my fault. Year ago I changed default order in the list of profiles (in Gps-master for Windows), such that Cycling was the first in the list. Today I reset it to the default settings and now have the same order as you. And moreover, when I choose Cycling profile, then I get  <Activity Sport="Biking"> in resulting tcx file. Looks like the problem is solved...

**Comment by mru00** [comment] 2015-07-18 19:38
Glad to hear that. But nevertheless the bin files showed the same activity. That would imply that your bin files were not running/cycling, but two times the same.

I went ahead and implemented a proper lookup via the activity name. This of course does not help if you give completely different names but when you reorder.


Please really confirm that the issue is fixed. Then I will kick the still-failing testcase and close this issue.

**Comment by knedlyk** [comment] 2015-07-18 19:44
Ok, tomorrow I'll make some experiments and inform you.

**Comment by knedlyk** [comment] 2015-07-20 13:11
Thanks, everything works as expected. When I set Cycling profile, I get "Biking" in the resulting tcx file, when I set Running profile, I get "Running" in tcx. I suppose you can close this issue.

**Comment by mru00** [comment] 2015-07-20 14:03
Perfect!

**Closed by mru00** 2015-07-20 14:03 UTC
Labels: bug, help wanted
